spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  servlet:
    multipart:
      location: E:/upload/demo2/
      max-file-size: 100MB
      max-request-size: 100MB


logging:
  level:
    root: info
    com.sinn: info
  file:
    name: log/forum-dev.log

mybatis-plus:
  type-aliases-package: com.sinn.pojo
  mapper-locations: classpath:mapper/*.xml   #ָ指定myBatis的核心配置文件与Mapper映射文件
  configuration:
    #控制台打印sql语句查看结果
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名转换规则
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-not-delete-value: 0
      logic-delete-value: 1
      id-type: auto
